"""Golden equivalence corpus for the canonical company merge policy.

The corpus and goldens freeze the behavior of the pre-load company
canonicalization exactly as produced before its promotion into
``sbir_etl.identity`` (spec: epistemic-tier-enforcement, R2). The goldens
were generated by ``canonicalize_companies_from_awards`` and must be
reproduced byte-identically by ``CanonicalMergePolicy.PRELOAD_V1``.
"""

import json
from pathlib import Path

import pandas as pd
import pytest


pytestmark = pytest.mark.fast

FIXTURE_ROOT = Path(__file__).resolve().parents[2] / "fixtures" / "identity"
CORPUS = FIXTURE_ROOT / "canonical_merge_corpus.csv"

# Two read variants: blanks as empty strings, and blanks as NaN (the shape
# production award frames actually carry). "N/A" DUNS survives only in the
# string variant; the NaN variant exercises pandas-missing handling.
GOLDEN_VARIANTS = {
    "canonical_merge_golden_strings.json": {"dtype": str, "keep_default_na": False},
    "canonical_merge_golden_nan.json": {"dtype": str},
}


def _canonical_map(frame: pd.DataFrame) -> dict[str, str]:
    from sbir_etl.utils.company_canonicalizer import canonicalize_companies_from_awards

    return canonicalize_companies_from_awards(frame, high_threshold=90, low_threshold=75)


@pytest.mark.parametrize("golden_name", sorted(GOLDEN_VARIANTS))
def test_golden_mapping_reproduced(golden_name: str) -> None:
    """The committed golden mapping is reproduced exactly from the corpus."""

    frame = pd.read_csv(CORPUS, **GOLDEN_VARIANTS[golden_name])
    golden = json.loads((FIXTURE_ROOT / golden_name).read_text(encoding="utf-8"))
    assert _canonical_map(frame) == golden
