"""Tests for the versioned canonical company merge policy.

The corpus and goldens freeze the behavior of the pre-load company
canonicalization exactly as produced before its promotion into
``sbir_etl.identity`` (spec: epistemic-tier-enforcement, R2). The goldens
were generated by the (now retired) ``canonicalize_companies_from_awards``
and are reproduced byte-identically by ``CanonicalMergePolicy.PRELOAD_V1`` —
the equivalence gate that permitted the promotion and deletion of the
exploratory implementation. The goldens are the durable frozen reference; the
remaining tests pin the individual clauses of the frozen contract (key
preference, thresholds, tie handling) so a future ``PRELOAD_V2`` cannot
silently ride in.
"""

import json
import random
from pathlib import Path

import pandas as pd
import pytest

from sbir_etl.identity.canonical_merge import (
    CanonicalMergePolicy,
    build_canonical_company_map,
)


pytestmark = pytest.mark.fast

FIXTURE_ROOT = Path(__file__).resolve().parents[2] / "fixtures" / "identity"
CORPUS = FIXTURE_ROOT / "canonical_merge_corpus.csv"

# Two read variants: blanks as empty strings, and blanks as NaN (the shape
# production award frames actually carry). "N/A" DUNS survives only in the
# string variant; the NaN variant exercises pandas-missing handling.
GOLDEN_VARIANTS = {
    "canonical_merge_golden_strings.json": {"dtype": str, "keep_default_na": False},
    "canonical_merge_golden_nan.json": {"dtype": str},
}


def _promoted(frame: pd.DataFrame) -> dict[str, str]:
    return build_canonical_company_map(frame, policy=CanonicalMergePolicy.PRELOAD_V1)


@pytest.mark.parametrize("golden_name", sorted(GOLDEN_VARIANTS))
def test_preload_v1_is_byte_identical_to_golden(golden_name: str) -> None:
    """PRELOAD_V1 reproduces the golden mapping exactly — the equivalence gate."""

    frame = pd.read_csv(CORPUS, **GOLDEN_VARIANTS[golden_name])
    golden = json.loads((FIXTURE_ROOT / golden_name).read_text(encoding="utf-8"))
    assert _promoted(frame) == golden


def test_empty_awards_returns_empty_map() -> None:
    assert _promoted(pd.DataFrame()) == {}


def test_key_preference_is_uei_then_duns_then_name() -> None:
    """A record's own key follows UEI > DUNS > normalized-name preference."""

    frame = pd.DataFrame(
        [
            {"company_name": "Alpha", "company_uei": "U1", "company_duns": "111111111"},
            {"company_name": "Beta", "company_uei": None, "company_duns": "222222222"},
            {"company_name": "Gamma Systems", "company_uei": None, "company_duns": None},
        ]
    )
    result = _promoted(frame)
    assert result["UEI:U1"] == "UEI:U1"
    assert result["DUNS:222222222"] == "DUNS:222222222"
    # PRELOAD_V1 uses MATCHING_V1 without enhanced abbreviations: "Systems" is
    # normalized (lower-cased, punctuation-stripped) but not abbreviated.
    assert result["NAME:gamma systems"] == "NAME:gamma systems"


def test_alternate_column_names_are_honored() -> None:
    """``company``/``uei``/``duns`` fall back when the prefixed names are absent."""

    frame = pd.DataFrame([{"company": "Delta", "uei": "U9", "duns": None}])
    assert _promoted(frame) == {"UEI:U9": "UEI:U9"}


def test_duns_match_overrides_uei_match() -> None:
    """Shared DUNS digits collapse records even across differing UEIs."""

    frame = pd.DataFrame(
        [
            {"company_name": "Helix One", "company_uei": "UA", "company_duns": "900000001"},
            {"company_name": "Helix Two", "company_uei": "UB", "company_duns": "900000001"},
        ]
    )
    result = _promoted(frame)
    # DUNS equality is applied last and wins: both point at the last DUNS holder.
    assert result["UEI:UA"] == "UEI:UB"
    assert result["UEI:UB"] == "UEI:UB"


def test_high_threshold_merges_near_duplicate_names() -> None:
    """A token-subset name pair ties at 100 and merges to the first-seen record."""

    frame = pd.DataFrame(
        [
            {"company_name": "Photon Dynamics", "company_uei": None, "company_duns": None},
            {"company_name": "Photon Dynamics Group", "company_uei": None, "company_duns": None},
        ]
    )
    result = _promoted(frame)
    assert result["NAME:photon dynamics group"] == "NAME:photon dynamics"
    assert result["NAME:photon dynamics"] == "NAME:photon dynamics"


def test_low_similarity_names_do_not_merge() -> None:
    """Sub-threshold fuzzy scores never merge — each keeps its own key."""

    frame = pd.DataFrame(
        [
            {"company_name": "Falcon Robotics", "company_uei": None, "company_duns": None},
            {"company_name": "Falcon Robotic Automation", "company_uei": None, "company_duns": None},
        ]
    )
    result = _promoted(frame)
    assert result["NAME:falcon robotics"] == "NAME:falcon robotics"
    assert result["NAME:falcon robotic automation"] == "NAME:falcon robotic automation"


def test_first_seen_record_wins_the_key() -> None:
    """Duplicate keys keep the first-seen record; later duplicates are dropped."""

    frame = pd.DataFrame(
        [
            {"company_name": "Orbit Labs", "company_uei": "UO", "company_duns": None},
            {"company_name": "ORBIT LABS INC", "company_uei": "UO", "company_duns": None},
        ]
    )
    assert _promoted(frame) == {"UEI:UO": "UEI:UO"}


def test_unsupported_policy_is_rejected() -> None:
    with pytest.raises(ValueError, match="unsupported canonical merge policy"):
        build_canonical_company_map(pd.DataFrame(), policy="preload-v99")  # type: ignore[arg-type]


def _random_corpus(seed: int, size: int) -> pd.DataFrame:
    stems = [
        "Acme Robotics", "Quantum Wave", "Blue River Analytics", "Orion Data Systems",
        "Helios Energy", "Cascade Micro", "Vector Dynamics", "Northstar Photonics",
        "Redwood Biotech", "Summit Aerospace", "Ironclad Security", "Granite Materials",
    ]
    suffixes = ["", " Inc", " Incorporated", " LLC", " Corp", " Group", " Technologies",
                " Systems", " Solutions", ", Inc.", " Co"]
    rng = random.Random(seed)
    rows = []
    for _ in range(size):
        name = rng.choice(stems) + rng.choice(suffixes)
        roll = rng.random()
        uei = f"UEI{rng.randint(1, 20):05d}" if roll < 0.3 else None
        duns = str(rng.randint(100000000, 100000020)) if 0.3 <= roll < 0.55 else None
        if rng.random() < 0.1:
            name = name.upper()
        rows.append({"company": name, "company_uei": uei, "company_duns": duns})
    return pd.DataFrame(rows)


@pytest.mark.parametrize("seed", range(25))
def test_merge_is_deterministic_and_maps_onto_known_keys(seed: int) -> None:
    """Canonicalization is stable and every canonical value is a known key.

    Determinism and the "canonical target is itself an original key" invariant
    hold the frozen behavior on randomized corpora without depending on the
    retired module, whose byte-identical equivalence is pinned by the golden
    gate above.
    """

    frame = _random_corpus(seed, size=40)
    mapping = _promoted(frame)
    assert _promoted(frame) == mapping  # deterministic across runs
    for canonical in mapping.values():
        assert canonical in mapping  # never points outside the resolved universe
