name: Wait for Neo4j
description: Waits for Neo4j service container to be ready by checking HTTP endpoint or TCP port

inputs:
  method:
    description: Check method - 'http' or 'tcp'
    required: false
    default: "http"
  uri:
    description: Neo4j HTTP URI (for http method, defaults to http://localhost:7474)
    required: false
    default: "http://localhost:7474"
  port:
    description: Neo4j TCP port (for tcp method, defaults to 7687)
    required: false
    default: "7687"
  timeout:
    description: Maximum wait time in seconds
    required: false
    default: "120"
  check-interval:
    description: Interval between checks in seconds
    required: false
    default: "5"

runs:
  using: composite
  steps:
    - name: Wait for Neo4j to be ready
      run: |
        set -eux
        METHOD="${{ inputs.method }}"
        TIMEOUT=${{ inputs.timeout }}
        INTERVAL=${{ inputs.check-interval }}
        ELAPSED=0

        if [ "$METHOD" = "tcp" ]; then
          PORT="${{ inputs.port }}"
          echo "Waiting for Neo4j to be ready on TCP port ${PORT}..."
          # Install netcat if not available
          if ! command -v nc >/dev/null 2>&1; then
            sudo apt-get update && sudo apt-get install -y --no-install-recommends netcat-openbsd
          fi

          until nc -z localhost ${PORT} || [ $ELAPSED -ge $TIMEOUT ]; do
            echo "Waiting for Neo4j on ${PORT}... (${ELAPSED}/${TIMEOUT}s elapsed)"
            sleep $INTERVAL
            ELAPSED=$((ELAPSED + INTERVAL))
          done
        else
          URI="${{ inputs.uri }}"
          echo "Waiting for Neo4j to be ready at ${URI}..."

          until curl -s -f -o /dev/null "${URI}" || [ $ELAPSED -ge $TIMEOUT ]; do
            echo "Neo4j not ready, sleeping for ${INTERVAL}s... (${ELAPSED}/${TIMEOUT}s elapsed)"
            sleep $INTERVAL
            ELAPSED=$((ELAPSED + INTERVAL))
          done
        fi

        if [ $ELAPSED -ge $TIMEOUT ]; then
          echo "❌ Neo4j did not become ready within ${TIMEOUT}s"
          exit 1
        fi

        echo "✅ Neo4j is ready!"
      shell: bash
