name: Setup Environment
description: Complete environment setup for CI jobs

inputs:
  python-version:
    description: Python version to use
    required: false
    default: "3.11"
  install-dev-deps:
    description: Install dev dependencies
    required: false
    default: "true"
  setup-aws:
    description: Setup AWS credentials
    required: false
    default: "false"
  aws-role-arn:
    description: AWS role ARN for OIDC
    required: false
    default: ""
  aws-region:
    description: AWS region
    required: false
    default: "us-east-2"

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup AWS credentials
      if: inputs.setup-aws == 'true'
      uses: ./.github/actions/setup-aws-credentials
      with:
        role-arn: ${{ inputs.aws-role-arn }}
        aws-region: ${{ inputs.aws-region }}

    - name: Setup Python and UV
      uses: ./.github/actions/setup-python-uv
      with:
        python-version: ${{ inputs.python-version }}
        install-dev-deps: ${{ inputs.install-dev-deps }}
        cache-venv: "true"
        cache-pytest: "false"
        install-pyreadstat: "false"
