name: Setup AWS Credentials
description: Configure AWS credentials using OIDC role assumption

inputs:
  role-arn:
    description: AWS IAM role ARN to assume (from secrets.AWS_ROLE_ARN)
    required: true
  aws-region:
    description: AWS region
    required: false
    default: "us-east-2"

runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role-arn }}
        aws-region: ${{ inputs.aws-region }}

