name: Detect Changes
description: Reusable change detection with configurable path filters

inputs:
  filters:
    description: YAML string of path filters (same format as dorny/paths-filter)
    required: true

outputs:
  # Common outputs
  docs-only:
    description: Whether only documentation files changed
    value: ${{ steps.filter.outputs.docs-only }}
  # CI-specific outputs
  performance:
    description: Whether performance-related files changed
    value: ${{ steps.filter.outputs.performance }}
  cet:
    description: Whether CET-related files changed
    value: ${{ steps.filter.outputs.cet }}
  transition:
    description: Whether transition-related files changed
    value: ${{ steps.filter.outputs.transition }}
  docker:
    description: Whether Docker-related files changed
    value: ${{ steps.filter.outputs.docker }}
  # Static analysis outputs
  code-changed:
    description: Whether code files changed
    value: ${{ steps.filter.outputs.code-changed }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4


    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: ${{ inputs.filters }}
