name: Detect Changes
description: |
  Detect which parts of the codebase changed using path filters.
  
  Note: This is a convenience wrapper. For direct output access, use dorny/paths-filter@v2 directly.
  When using this action, outputs are available via steps.<step-id>.outputs.<filter-name>
  where <step-id> is the ID you assign to this step.

inputs:
  filters:
    description: YAML string defining path filters (see dorny/paths-filter for format)
    required: true

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Detect changes
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: ${{ inputs.filters }}

