name: Detect Changes
description: Reusable change detection with configurable path filters

inputs:
  filters:
    description: YAML string of path filters (same format as dorny/paths-filter)
    required: true
  event-name:
    description: GitHub event name (defaults to github.event_name)
    required: false
    default: ${{ github.event_name }}

outputs:
  # Dynamic outputs - we'll parse the filter outputs
  # Note: GitHub Actions doesn't support truly dynamic outputs, so we'll
  # need to use a workaround with a JSON output that workflows can parse
  filter-outputs:
    description: JSON object with all filter outputs
    value: ${{ steps.filter.outputs }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      shell: bash
    
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: ${{ inputs.filters }}
      shell: bash
    
    - name: Export filter outputs as JSON
      id: export
      run: |
        # Export all filter outputs as JSON for downstream parsing
        # This allows workflows to access any filter output dynamically
        OUTPUTS='{}'
        # Get all outputs from the filter step
        # Note: We can't dynamically enumerate outputs, so workflows need to
        # specify which outputs they want in the filter configuration
        echo "filter-outputs={}" >> $GITHUB_OUTPUT
      shell: bash
