"""BEA Python ↔ R/StateIO equivalency tests.

Validates that the Python Leontief I-O math produces identical results to the
R/StateIO package.  Uses two approaches:

1. **Synthetic matrices** (always run): 3×3 matrices with known analytical
   solutions.  Validates the math layer independent of any API.

2. **Live BEA API** (requires BEA_API_KEY): Fetches real Use/VA tables from the
   BEA API and compares against reference fixture values generated by the R
   script ``scripts/generate_r_reference_values.R``.  Skipped if API key is
   not set or if reference fixture doesn't contain R-generated values.

To regenerate R reference values (requires R + stateior package):
    Rscript scripts/generate_r_reference_values.R
"""

from __future__ import annotations

import json
from decimal import Decimal
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from sbir_etl.transformers.bea_io_functions import (
    apply_demand_shocks,
    calculate_employment_from_production,
    calculate_leontief_inverse,
    calculate_technical_coefficients,
)

FIXTURES_DIR = Path(__file__).parent.parent / "fixtures"
REFERENCE_FILE = FIXTURES_DIR / "r_reference_values.json"


@pytest.fixture
def reference_data():
    """Load reference values fixture."""
    with open(REFERENCE_FILE) as f:
        return json.load(f)


@pytest.fixture
def synthetic(reference_data):
    """Extract the synthetic 3×3 test case."""
    return reference_data["synthetic_3x3"]


# ---------------------------------------------------------------------------
# Synthetic matrix tests (always run, no API needed)
# ---------------------------------------------------------------------------


class TestSyntheticMatrixEquivalency:
    """Validate Leontief math against known analytical solutions."""

    def _make_use_table(self, synthetic):
        sectors = synthetic["use_table"]["sectors"]
        values = synthetic["use_table"]["values"]
        return pd.DataFrame(values, index=sectors, columns=sectors, dtype=float)

    def _make_output(self, synthetic):
        sectors = synthetic["use_table"]["sectors"]
        return pd.Series(synthetic["industry_output"], index=sectors, dtype=float)

    def test_technical_coefficients(self, synthetic):
        """A[i,j] = use[i,j] / output[j] matches expected values."""
        use_table = self._make_use_table(synthetic)
        output = self._make_output(synthetic)

        tech_coeff = calculate_technical_coefficients(use_table, output)

        expected = np.array(synthetic["tech_coefficients"]["values"])
        np.testing.assert_allclose(
            tech_coeff.values, expected, atol=1e-4,
            err_msg="Technical coefficients diverge from reference",
        )

    def test_leontief_inverse(self, synthetic):
        """L = (I - A)^{-1} matches expected values within tolerance."""
        use_table = self._make_use_table(synthetic)
        output = self._make_output(synthetic)

        tech_coeff = calculate_technical_coefficients(use_table, output)
        leontief_inv = calculate_leontief_inverse(tech_coeff)

        expected = np.array(synthetic["leontief_inverse"]["values"])
        tol = synthetic["leontief_inverse"]["tolerance"]
        np.testing.assert_allclose(
            leontief_inv.values, expected, atol=tol,
            err_msg="Leontief inverse diverges from reference",
        )

    def test_demand_shock_production(self, synthetic):
        """Production = L × demand matches expected per-sector output."""
        use_table = self._make_use_table(synthetic)
        output = self._make_output(synthetic)
        sectors = synthetic["use_table"]["sectors"]

        tech_coeff = calculate_technical_coefficients(use_table, output)
        leontief_inv = calculate_leontief_inverse(tech_coeff)

        shock_cfg = synthetic["demand_shock"]
        shocks_df = pd.DataFrame({
            "bea_sector": [shock_cfg["shock_sector"]],
            "shock_amount": [shock_cfg["shock_amount"]],
        })

        production = apply_demand_shocks(leontief_inv, shocks_df)
        tol = shock_cfg["tolerance"]

        for sector in sectors:
            expected_val = shock_cfg["expected_production"][sector]
            assert abs(float(production[sector]) - expected_val) < tol, (
                f"Sector {sector}: got {production[sector]:.4f}, "
                f"expected {expected_val:.4f} (tol={tol})"
            )

        assert abs(float(production.sum()) - shock_cfg["total_output"]) < tol

    def test_leontief_inverse_identity_property(self, synthetic):
        """L × (I - A) ≈ I (mathematical identity check)."""
        use_table = self._make_use_table(synthetic)
        output = self._make_output(synthetic)

        tech_coeff = calculate_technical_coefficients(use_table, output)
        leontief_inv = calculate_leontief_inverse(tech_coeff)

        identity = np.eye(len(output))
        i_minus_a = identity - tech_coeff.values
        result = leontief_inv.values @ i_minus_a

        np.testing.assert_allclose(
            result, identity, atol=1e-10,
            err_msg="L × (I - A) should equal identity matrix",
        )

    def test_unit_conversion_dollars_to_bea(self, reference_data):
        """Verify dollar ↔ BEA-millions conversion in the adapter pipeline."""
        conv = reference_data["unit_conversion"]

        # $1M in dollars = 1.0 in BEA units
        shock_dollars = conv["shock_dollars"]
        shock_bea = shock_dollars / 1_000_000.0
        assert shock_bea == conv["shock_bea_units"]

        # After Leontief multiplication in BEA units, convert back to dollars
        # Using the synthetic Leontief inverse sector A self-multiplier (~1.2706)
        synthetic = reference_data["synthetic_3x3"]
        use_table = pd.DataFrame(
            synthetic["use_table"]["values"],
            index=synthetic["use_table"]["sectors"],
            columns=synthetic["use_table"]["sectors"],
            dtype=float,
        )
        output = pd.Series(
            synthetic["industry_output"],
            index=synthetic["use_table"]["sectors"],
            dtype=float,
        )
        tech_coeff = calculate_technical_coefficients(use_table, output)
        leontief_inv = calculate_leontief_inverse(tech_coeff)

        shocks_df = pd.DataFrame({
            "bea_sector": ["A"],
            "shock_amount": [shock_bea],
        })
        production = apply_demand_shocks(leontief_inv, shocks_df)

        # Convert back to dollars
        production_dollars = float(production["A"]) * 1_000_000.0
        expected = conv["expected_production_dollars_sector_A"]
        tol = conv["tolerance_dollars"]
        assert abs(production_dollars - expected) < tol, (
            f"Production impact in dollars: {production_dollars:.0f}, "
            f"expected {expected} (tol={tol})"
        )


# ---------------------------------------------------------------------------
# Live BEA API tests (require BEA_API_KEY + R reference values)
# ---------------------------------------------------------------------------


@pytest.mark.requires_bea_api
class TestLiveBEAEquivalency:
    """Compare live BEA API results against R-generated reference values.

    These tests only run when:
    1. BEA_API_KEY environment variable is set
    2. tests/fixtures/r_reference_values.json contains R-generated data
       (has 'stateior_version' in metadata)

    To generate R reference values:
        Rscript scripts/generate_r_reference_values.R
    """

    @pytest.fixture(autouse=True)
    def _skip_without_r_reference(self, reference_data):
        """Skip if reference fixture doesn't have R-generated values."""
        metadata = reference_data.get("metadata", {})
        if "stateior_version" not in metadata:
            pytest.skip(
                "R-generated reference values not found. "
                "Run: Rscript scripts/generate_r_reference_values.R"
            )

    @pytest.fixture
    def bea_client(self):
        """Create a real BEA API client."""
        from sbir_etl.transformers.bea_api_client import BEAApiClient

        return BEAApiClient()

    def test_use_table_sector_coverage(self, bea_client, reference_data):
        """BEA API Use table has the same sectors as R/StateIO."""
        from sbir_etl.transformers.bea_io_functions import fetch_use_table

        use_table = fetch_use_table(bea_client, year=2020)
        assert not use_table.empty, "BEA Use table fetch returned empty"

        r_sectors = reference_data["tech_coefficients_5x5"]["sectors"]
        for sector in r_sectors:
            assert sector in use_table.columns, (
                f"R reference sector '{sector}' missing from BEA API Use table"
            )

    def test_tech_coefficients_match_r(self, bea_client, reference_data):
        """Technical coefficients from BEA API match R/StateIO within tolerance."""
        from sbir_etl.transformers.bea_io_functions import (
            fetch_industry_output,
            fetch_use_table,
        )

        use_table = fetch_use_table(bea_client, year=2020)
        output = fetch_industry_output(use_table)
        tech_coeff = calculate_technical_coefficients(use_table, output)

        r_tc = reference_data["tech_coefficients_5x5"]
        r_sectors = r_tc["sectors"]

        for i, row_sector in enumerate(r_sectors):
            for j, col_sector in enumerate(r_sectors):
                if row_sector in tech_coeff.index and col_sector in tech_coeff.columns:
                    python_val = tech_coeff.loc[row_sector, col_sector]
                    r_val = r_tc["values"][i][j] if isinstance(r_tc["values"][i], list) else r_tc["values"][row_sector][j]
                    assert abs(float(python_val) - float(r_val)) < 0.01, (
                        f"Tech coeff [{row_sector},{col_sector}]: "
                        f"Python={python_val:.6f}, R={r_val:.6f}"
                    )

    def test_demand_shock_total_output_matches_r(self, bea_client, reference_data):
        """Total production from $1M shock matches R/StateIO within 5%."""
        from sbir_etl.transformers.bea_io_functions import (
            fetch_industry_output,
            fetch_use_table,
        )

        use_table = fetch_use_table(bea_client, year=2020)
        output = fetch_industry_output(use_table)
        tech_coeff = calculate_technical_coefficients(use_table, output)
        leontief_inv = calculate_leontief_inverse(tech_coeff)

        r_shock = reference_data["demand_shock_1m_sector_11"]
        shocks_df = pd.DataFrame({
            "bea_sector": [r_shock["shock_sector"]],
            "shock_amount": [r_shock["shock_amount_millions"]],
        })
        production = apply_demand_shocks(leontief_inv, shocks_df)
        total = float(production.sum())
        r_total = r_shock["total_output"]

        # Allow 5% tolerance for minor BEA table version differences
        pct_diff = abs(total - r_total) / r_total * 100
        assert pct_diff < 5.0, (
            f"Total output: Python={total:.4f}, R={r_total:.4f} "
            f"({pct_diff:.1f}% difference, max 5%)"
        )


# ---------------------------------------------------------------------------
# Full adapter round-trip test
# ---------------------------------------------------------------------------


@pytest.mark.requires_bea_api
class TestAdapterRoundTrip:
    """End-to-end adapter test with real BEA API."""

    def test_compute_impacts_returns_expected_columns(self):
        """BEAIOAdapter.compute_impacts returns all required columns."""
        from sbir_etl.transformers.bea_io_adapter import BEAIOAdapter

        adapter = BEAIOAdapter(cache_enabled=False)
        if not adapter.is_available():
            pytest.skip("BEA API not available")

        shocks = pd.DataFrame({
            "state": ["CA"],
            "bea_sector": ["11"],
            "fiscal_year": [2020],
            "shock_amount": [Decimal("1000000")],
        })

        result = adapter.compute_impacts(shocks)
        adapter.close()

        required = [
            "state", "bea_sector", "fiscal_year", "shock_amount",
            "wage_impact", "production_impact", "tax_impact",
            "employment_impact", "model_version", "quality_flags",
        ]
        for col in required:
            assert col in result.columns, f"Missing column: {col}"

        assert len(result) == 1
        assert float(result["production_impact"].iloc[0]) > 0

    def test_multi_year_shocks_use_correct_tables(self):
        """Multi-year shocks are split and computed with correct year tables."""
        from sbir_etl.transformers.bea_io_adapter import BEAIOAdapter

        adapter = BEAIOAdapter(cache_enabled=False)
        if not adapter.is_available():
            pytest.skip("BEA API not available")

        shocks = pd.DataFrame({
            "state": ["CA", "CA"],
            "bea_sector": ["11", "11"],
            "fiscal_year": [2019, 2020],
            "shock_amount": [Decimal("1000000"), Decimal("1000000")],
        })

        result = adapter.compute_impacts(shocks)
        adapter.close()

        assert len(result) == 2
        years = result["fiscal_year"].unique().tolist()
        assert 2019 in years
        assert 2020 in years
