name: Upload Artifacts
description: Upload workflow artifacts with common patterns

inputs:
  name:
    description: Artifact name
    required: true
  path:
    description: Path(s) to upload (supports multi-line YAML)
    required: true
  retention-days:
    description: Number of days to retain artifacts
    required: false
    default: "7"
  if-no-files-found:
    description: Behavior when no files found (warn, error, ignore)
    required: false
    default: "warn"

runs:
  using: composite
  steps:
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
        retention-days: ${{ inputs.retention-days }}
        if-no-files-found: ${{ inputs.if-no-files-found }}

