"""Dagster assets for SBIR ETL pipeline."""

from .example_assets import raw_sbir_data, validated_sbir_data
from .uspto_assets import (
    parsed_uspto_assignees,
    parsed_uspto_assignments,
    parsed_uspto_assignors,
    parsed_uspto_conveyances,
    parsed_uspto_documentids,
    raw_uspto_assignees,
    raw_uspto_assignments,
    raw_uspto_assignors,
    raw_uspto_conveyances,
    raw_uspto_documentids,
    uspto_assignees_parsing_check,
    uspto_assignments_parsing_check,
    uspto_assignors_parsing_check,
    uspto_conveyances_parsing_check,
    uspto_documentids_parsing_check,
)
from .uspto_neo4j_loading_assets import (
    assignment_load_success_rate,
    neo4j_patent_assignments,
    neo4j_patent_entities,
    neo4j_patent_relationships,
    neo4j_patents,
    patent_load_success_rate,
    patent_relationship_cardinality,
)
from .uspto_transformation_assets import (
    transformed_patent_assignments,
    transformed_patent_entities,
    transformed_patents,
    uspto_company_linkage_check,
    uspto_transformation_success_check,
)
from .uspto_validation_assets import (
    uspto_completeness_asset_check,
    uspto_referential_asset_check,
    uspto_rf_id_asset_check,
    validated_uspto_assignments,
)

__all__ = [
    "raw_sbir_data",
    "validated_sbir_data",
    "raw_uspto_assignments",
    "raw_uspto_assignees",
    "raw_uspto_assignors",
    "raw_uspto_documentids",
    "raw_uspto_conveyances",
    "parsed_uspto_assignments",
    "parsed_uspto_assignees",
    "parsed_uspto_assignors",
    "parsed_uspto_documentids",
    "parsed_uspto_conveyances",
    "uspto_assignments_parsing_check",
    "uspto_assignees_parsing_check",
    "uspto_assignors_parsing_check",
    "uspto_documentids_parsing_check",
    "uspto_conveyances_parsing_check",
    "validated_uspto_assignments",
    "uspto_rf_id_asset_check",
    "uspto_completeness_asset_check",
    "uspto_referential_asset_check",
    "transformed_patent_assignments",
    "transformed_patents",
    "transformed_patent_entities",
    "uspto_transformation_success_check",
    "uspto_company_linkage_check",
    "neo4j_patents",
    "neo4j_patent_assignments",
    "neo4j_patent_entities",
    "neo4j_patent_relationships",
    "patent_load_success_rate",
    "assignment_load_success_rate",
    "patent_relationship_cardinality",
]
