name: Setup Python and UV
description: Standardized Python setup with UV package manager and dependency installation

inputs:
  python-version:
    description: Python version to use
    required: false
    default: "3.11"
  install-dev-deps:
    description: Whether to install dev dependencies
    required: false
    default: "true"
  cache-venv:
    description: Whether to cache virtual environment
    required: false
    default: "true"
  cache-pytest:
    description: Whether to cache pytest cache
    required: false
    default: "false"
  install-pyreadstat:
    description: Whether to install pyreadstat
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'uv'
      shell: bash

    - name: Cache UV installation
      uses: actions/cache@v4
      id: cache-uv
      with:
        path: |
          $HOME/.cargo/bin/uv
          $HOME/.local/bin/uv
        key: uv-binary-${{ runner.os }}-latest
        restore-keys: |
          uv-binary-${{ runner.os }}-
      shell: bash

    - name: Install UV
      if: steps.cache-uv.outputs.cache-hit != 'true'
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      shell: bash

    - name: Add UV to PATH
      if: steps.cache-uv.outputs.cache-hit == 'true'
      run: |
        # UV might be in cargo bin or local bin
        if [ -f "$HOME/.cargo/bin/uv" ]; then
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        elif [ -f "$HOME/.local/bin/uv" ]; then
          echo "$HOME/.local/bin" >> $GITHUB_PATH
        else
          # Fallback: install if not found in cache
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        fi
      shell: bash

    - name: Cache UV virtual environment
      if: inputs.cache-venv == 'true'
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles('**/uv.lock') }}
        restore-keys: |
          venv-${{ runner.os }}-${{ inputs.python-version }}-

    - name: Cache pytest cache
      if: inputs.cache-pytest == 'true'
      uses: actions/cache@v4
      with:
        path: .pytest_cache
        key: pytest-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles('tests/**/*.py', 'src/**/*.py') }}
        restore-keys: |
          pytest-${{ runner.os }}-${{ inputs.python-version }}-

    - name: Install dependencies
      run: |
        if [ "${{ inputs.install-dev-deps }}" = "true" ]; then
          uv sync
        else
          uv sync --no-dev
        fi
      shell: bash

    - name: Cache pip packages (for pyreadstat)
      if: inputs.install-pyreadstat == 'true'
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: pip-packages-${{ runner.os }}-${{ hashFiles('**/uv.lock') }}
        restore-keys: |
          pip-packages-${{ runner.os }}-

    - name: Install pyreadstat
      if: inputs.install-pyreadstat == 'true'
      run: |
        # pyreadstat is in dev dependencies but needed for tests
        # duckdb is already installed via uv sync (it's in main dependencies)
        uv pip install --cache-dir ~/.cache/pip pyreadstat
      shell: bash


